shopware:
   admin_worker:
      enable_admin_worker: false

monolog:
   handlers:
      main:
         level: error
         buffer_size: 30
      business_event_handler_buffer:
         level: error